const mongoose = require ('mongoose')
const { Schema } = mongoose

const schemaQ5 = new Schema ({
    title1: String,
    res1: String,
    valor1: Number,
    res2: String,
    valor2: Number,
    res3: String,
    valor3: Number,
    res4: String,
    valor4: Number,
    res5: String,
    title2: String,
    valor5: Number,
    res6: String,
    valor6: Number,
    res7: String,
    valor7: Number,
    res8: String,
    valor8: Number,
    title3: String,
    res9: String,
    valor9: Number,
    res10: String,
    valor10: Number,
    res11: String,
    valor11: Number,
    res12: String,
    valor12: Number,
    title4: String,
    res13: String,
    valor13: Number,
    res14: String,
    valor14: Number,
    res15: String,
    valor15: Number,
    res16: String,
    valor16: Number,
    title5: String,
    res17: String,
    valor17: Number,
    res18: String,
    valor18: Number,
    res19: String,
    valor19: Number,
    res20: String,
    valor20: Number,
},{
    timestamps: true
})

module.exports = mongoose.model('Q5', schemaQ5)